import json

games = [
  {'id': 1, 'program': 'ACEYDU', 'title': 'Acey-Ducey', 'description': 'Play acey-ducey with the computer', 'page': 13, 'dialect': 'BASIC-PLUS', 'category': 'card'},
  {'id': 2, 'program': 'AMAZIN', 'title': 'Amazing', 'description': 'Computer constructs a maze', 'page': 15, 'dialect': 'BASIC-PLUS', 'category': 'puzzle'},
  {'id': 3, 'program': 'ANIMAL', 'title': 'Animal', 'description': 'Computer guesses animals and learns new ones from you', 'page': 17, 'dialect': 'BASIC-PLUS', 'category': 'learning'},
  {'id': 4, 'program': 'AWARI', 'title': 'Awari', 'description': 'Ancient game of rotating beans in pits', 'page': 19, 'dialect': 'BASIC-PLUS', 'category': 'board'},
  {'id': 5, 'program': 'BAGLES', 'title': 'Bagels', 'description': 'Guess a mystery 3-digit number by logic', 'page': 22, 'dialect': 'BASIC-PLUS', 'category': 'guessing'},
  {'id': 6, 'program': 'BANNER', 'title': 'Banner', 'description': 'Prints any message on a large banner', 'page': 24, 'dialect': 'EduSystem 50', 'category': 'utility'},
  {'id': 7, 'program': 'BASBAL', 'title': 'Baseball', 'description': 'Baseball game', 'page': 26, 'dialect': 'EduSystem 15/30/35', 'category': 'sports'},
  {'id': 8, 'program': 'BASKET', 'title': 'Basketball', 'description': 'Basketball game', 'page': 29, 'dialect': 'Dartmouth?', 'category': 'sports'},
  {'id': 9, 'program': 'BATNUM', 'title': 'Battle Number', 'description': 'Match wits in a battle of numbers vs. the computer', 'page': 32, 'dialect': 'Dartmouth?', 'category': 'guessing'},
  {'id': 10, 'program': 'BATTLE', 'title': 'Battle', 'description': 'Decode a matrix to locate enemy battleship', 'page': 34, 'dialect': 'HP?', 'category': 'strategy'},
  {'id': 11, 'program': 'BINGO', 'title': 'Bingo', 'description': 'Computer prints your card and calls the numbers', 'page': 36, 'dialect': 'DECsystem 10', 'category': 'card'},
  {'id': 12, 'program': 'BLKJAC', 'title': 'Blackjack', 'description': 'Blackjack (very comprehensive), Las Vegas rules', 'page': 39, 'dialect': 'BASIC-PLUS', 'category': 'card'},
  {'id': 13, 'program': 'BLKJAK', 'title': 'Blackjack (Standard)', 'description': 'Blackjack (standard game)', 'page': 42, 'dialect': 'EduSystem 30', 'category': 'card'},
  {'id': 14, 'program': 'BOAT', 'title': 'Boat', 'description': 'Destroy a gunboat from your submarine', 'page': 43, 'dialect': 'generic', 'category': 'strategy'},
  {'id': 15, 'program': 'BOMBER', 'title': 'Bomber', 'description': 'Fly World War II bombing missions', 'page': 45, 'dialect': 'Unclear', 'category': 'action'},
  {'id': 16, 'program': 'BOUNCE', 'title': 'Bounce', 'description': 'Plot a bouncing ball', 'page': 47, 'dialect': 'generic', 'category': 'simulation'},
  {'id': 17, 'program': 'BOWL', 'title': 'Bowling', 'description': 'Bowling at the neighborhood lanes', 'page': 48, 'dialect': 'BASIC-PLUS', 'category': 'sports'},
  {'id': 18, 'program': 'BOXING', 'title': 'Boxing', 'description': '3-round Olympic boxing match', 'page': 50, 'dialect': 'generic DEC', 'category': 'sports'},
  {'id': 19, 'program': 'BUG', 'title': 'Bug', 'description': 'Roll dice vs. the computer to draw a bug', 'page': 52, 'dialect': 'HP?', 'category': 'dice'},
  {'id': 20, 'program': 'BULCOW', 'title': 'Bulls and Cows', 'description': 'Guess a mystery 5-digit number vs. the computer', 'page': 55, 'dialect': 'Dartmouth?', 'category': 'guessing'},
  {'id': 21, 'program': 'BULEYE', 'title': 'Bullseye', 'description': 'Throw darts', 'page': 57, 'dialect': 'BASIC-PLUS', 'category': 'action'},
  {'id': 22, 'program': 'BULL', 'title': 'Bull', 'description': "You're the matador in a championship bullfight", 'page': 59, 'dialect': 'generic DEC', 'category': 'simulation'},
  {'id': 23, 'program': 'BUNNY', 'title': 'Bunny', 'description': 'Computer drawing of the Playboy bunny', 'page': 62, 'dialect': 'No code', 'category': 'art'},
  {'id': 24, 'program': 'BUZZWD', 'title': 'Buzzword', 'description': 'Compose your speeches with the latest buzzwords', 'page': 63, 'dialect': 'EduSystem', 'category': 'utility'},
  {'id': 25, 'program': 'CALNDR', 'title': 'Calendar', 'description': 'Calendar for any year', 'page': 65, 'dialect': 'EduSystem', 'category': 'utility'},
  {'id': 26, 'program': 'CAN-AM', 'title': 'Can-Am', 'description': 'Drive a Group 7 car in a Can-Am road race', 'page': 67, 'dialect': 'Dartmouth', 'category': 'simulation'},
  {'id': 27, 'program': 'CHANGE', 'title': 'Change', 'description': 'Computer imitates a cashier', 'page': 72, 'dialect': 'EduSystem', 'category': 'educational'},
  {'id': 28, 'program': 'CHECKR', 'title': 'Checkers', 'description': 'Game of checkers', 'page': 73, 'dialect': 'generic', 'category': 'board'},
  {'id': 29, 'program': 'CHEMST', 'title': 'Chemist', 'description': 'Dilute kryptocyanic acid to make it harmless', 'page': 76, 'dialect': 'generic', 'category': 'educational'},
  {'id': 30, 'program': 'CHIEF', 'title': 'Chief', 'description': 'Silly arithmetic drill', 'page': 77, 'dialect': 'EduSystem', 'category': 'educational'},
  {'id': 31, 'program': 'CHOMP', 'title': 'Chomp', 'description': 'Eat a cookie avoiding the poison piece (2 or more)', 'page': 78, 'dialect': 'generic', 'category': 'board'},
  {'id': 32, 'program': 'CIVILW', 'title': 'Civil War', 'description': 'Fight the Civil War', 'page': 80, 'dialect': 'generic', 'category': 'strategy'},
  {'id': 33, 'program': 'CRAPS', 'title': 'Craps', 'description': 'Play craps (dice), Las Vegas style', 'page': 83, 'dialect': 'BASIC-8', 'category': 'dice'},
  {'id': 34, 'program': 'CUBE', 'title': 'Cube', 'description': 'Negotiate a 3-D cube avoiding hidden landmines', 'page': 85, 'dialect': 'generic', 'category': 'puzzle'},
  {'id': 35, 'program': 'DIAMND', 'title': 'Diamond', 'description': 'Prints 1-page diamond patterns', 'page': 87, 'dialect': 'BASIC-8/EduSystem', 'category': 'art'},
  {'id': 36, 'program': 'DICE', 'title': 'Dice', 'description': 'Summarizes dice rolls', 'page': 89, 'dialect': 'BASIC-8/EduSystem', 'category': 'dice'},
  {'id': 37, 'program': 'DIGITS', 'title': 'Digits', 'description': 'Computer tries to guess digits you select at random', 'page': 91, 'dialect': 'BASIC-PLUS?', 'category': 'guessing'},
  {'id': 38, 'program': 'DOGS', 'title': 'Dogs', 'description': 'Penny arcade dog race', 'page': 93, 'dialect': 'EduSystem 50', 'category': 'simulation'},
  {'id': 39, 'program': 'EVEN', 'title': 'Even Wins', 'description': 'Take objects from a pile - try to end with an even number', 'page': 96, 'dialect': 'generic', 'category': 'strategy'},
  {'id': 40, 'program': 'EVEN1', 'title': 'Even Wins II', 'description': 'Same as EVEN - computer improves its play', 'page': 98, 'dialect': 'generic', 'category': 'strategy'},
  {'id': 41, 'program': 'FIPFOP', 'title': 'Fip-Fop', 'description': 'Solitaire logic game - change a row of Xs to Os', 'page': 99, 'dialect': 'generic', 'category': 'puzzle'},
  {'id': 42, 'program': 'FOOTBL', 'title': 'Football (Pro)', 'description': 'Professional football (very comprehensive)', 'page': 101, 'dialect': 'BASIC-PLUS', 'category': 'sports'},
  {'id': 43, 'program': 'FOOTBAL', 'title': 'Football (High School)', 'description': 'High School football', 'page': 104, 'dialect': 'generic', 'category': 'sports'},
  {'id': 44, 'program': 'FURS', 'title': 'Furs', 'description': 'Trade furs with the white man', 'page': 106, 'dialect': 'generic', 'category': 'strategy'},
  {'id': 45, 'program': 'GOLF', 'title': 'Golf', 'description': 'Golf game - choose your clubs and swing', 'page': 109, 'dialect': 'generic', 'category': 'sports'},
  {'id': 46, 'program': 'GOMOKO', 'title': 'Gomoko', 'description': 'Ancient board game of logic and strategy', 'page': 110, 'dialect': 'generic', 'category': 'board'},
  {'id': 47, 'program': 'GUESS', 'title': 'Guess', 'description': 'Guess a mystery number - computer gives you clues', 'page': 113, 'dialect': 'EduSystem 20', 'category': 'guessing'},
  {'id': 48, 'program': 'GUNNER', 'title': 'Gunner', 'description': 'Fire a cannon at a stationary target', 'page': 115, 'dialect': 'generic', 'category': 'action'},
  {'id': 49, 'program': 'GUNER1', 'title': 'Gunner II', 'description': 'Fire a cannon at a moving target', 'page': 116, 'dialect': 'generic', 'category': 'action'},
  {'id': 50, 'program': 'HANG', 'title': 'Hangman', 'description': 'Hangman word guessing game', 'page': 118, 'dialect': 'BASIC-PLUS', 'category': 'word'},
  {'id': 51, 'program': 'HELLO', 'title': 'Hello', 'description': 'Computer becomes your friendly psychiatrist', 'page': 120, 'dialect': 'EduSystem 25', 'category': 'simulation'},
  {'id': 52, 'program': 'HEX', 'title': 'Hexapawn', 'description': 'Hexapawn game', 'page': 122, 'dialect': 'BASIC-PLUS', 'category': 'board'},
  {'id': 53, 'program': 'HI-LO', 'title': 'Hi-Lo', 'description': 'Try to hit the mystery jackpot', 'page': 124, 'dialect': 'generic', 'category': 'guessing'},
  {'id': 54, 'program': 'HI-Q', 'title': 'Hi-Q', 'description': 'Try to remove all the pegs from a board', 'page': 126, 'dialect': 'generic', 'category': 'puzzle'},
  {'id': 55, 'program': 'HMRABI', 'title': 'Hammurabi', 'description': 'Govern the ancient city-state of Sumeria', 'page': 128, 'dialect': 'generic', 'category': 'strategy'},
  {'id': 56, 'program': 'HOCKEY', 'title': 'Hockey', 'description': 'Ice hockey vs. Cornell', 'page': 130, 'dialect': 'generic', 'category': 'sports'},
  {'id': 57, 'program': 'HORSES', 'title': 'Horses', 'description': 'Off-track betting on a horse race', 'page': 133, 'dialect': 'generic', 'category': 'simulation'},
  {'id': 58, 'program': 'HURKLE', 'title': 'Hurkle', 'description': 'Find the Hurkle hiding on a 10x10 grid', 'page': 135, 'dialect': 'BASIC-8', 'category': 'guessing'},
  {'id': 59, 'program': 'KINEMA', 'title': 'Kinema', 'description': 'Drill in simple kinematics', 'page': 137, 'dialect': 'generic', 'category': 'educational'},
  {'id': 60, 'program': 'KING', 'title': 'King', 'description': 'Govern a modern island kingdom wisely', 'page': 138, 'dialect': 'BASIC-PLUS', 'category': 'strategy'},
  {'id': 61, 'program': 'LETTER', 'title': 'Letter', 'description': 'Guess a mystery letter - computer gives you clues', 'page': 141, 'dialect': 'EduSystem 30', 'category': 'guessing'},
  {'id': 62, 'program': 'LIFE', 'title': 'Life', 'description': "John Conway's Game of Life", 'page': 143, 'dialect': 'BASIC-PLUS', 'category': 'simulation'},
  {'id': 63, 'program': 'LIFE-2', 'title': 'Life II', 'description': 'Competitive game of life (2 or more players)', 'page': 146, 'dialect': 'BASIC-PLUS', 'category': 'board'},
  {'id': 64, 'program': 'LITQZ', 'title': 'Literature Quiz', 'description': "Children's literature quiz", 'page': 148, 'dialect': 'EduSystem 30', 'category': 'educational'},
  {'id': 65, 'program': 'MATHD', 'title': 'Math Dice', 'description': "Children's arithmetic drill using pictures of dice", 'page': 151, 'dialect': 'EduSystem 30', 'category': 'educational'},
  {'id': 66, 'program': 'MNOPLY', 'title': 'Monopoly', 'description': 'Monopoly for 2 players', 'page': 153, 'dialect': 'BASIC-PLUS', 'category': 'board'},
  {'id': 67, 'program': 'MUGWMP', 'title': 'Mugwump', 'description': 'Locate 4 Mugwumps hiding on a 10x10 grid', 'page': 156, 'dialect': 'BASIC-PLUS', 'category': 'guessing'},
  {'id': 68, 'program': 'NICOMA', 'title': 'Nicoma', 'description': 'Computer guesses number you think of', 'page': 158, 'dialect': 'BASIC-PLUS', 'category': 'guessing'},
  {'id': 69, 'program': 'NIM', 'title': 'Nim', 'description': 'Chinese game of Nim', 'page': 160, 'dialect': 'EduSystem 30?', 'category': 'strategy'},
  {'id': 70, 'program': 'NUMBER', 'title': 'Number', 'description': 'Silly number matching game', 'page': 162, 'dialect': 'EduSystem 30', 'category': 'educational'},
  {'id': 71, 'program': '1CHECK', 'title': 'One Check', 'description': 'Challenging game to remove checkers from a board', 'page': 163, 'dialect': 'unknown', 'category': 'board'},
  {'id': 72, 'program': 'ORBIT', 'title': 'Orbit', 'description': 'Destroy an orbiting germ-laiden enemy spaceship', 'page': 165, 'dialect': 'generic', 'category': 'action'},
  {'id': 73, 'program': 'PIZZA', 'title': 'Pizza', 'description': 'Deliver pizzas successfully', 'page': 167, 'dialect': 'generic', 'category': 'simulation'},
  {'id': 74, 'program': 'POETRY', 'title': 'Poetry', 'description': 'Computer composes poetry in 4-part harmony', 'page': 169, 'dialect': 'generic', 'category': 'art'},
  {'id': 75, 'program': 'POET', 'title': 'Poet', 'description': 'Computer composes random poetry', 'page': 171, 'dialect': 'EduSystem ?', 'category': 'art'},
  {'id': 76, 'program': 'POKER', 'title': 'Poker', 'description': 'Poker game', 'page': 172, 'dialect': 'BASIC-8', 'category': 'card'},
  {'id': 77, 'program': 'QUBIC', 'title': 'Qubic', 'description': '3-dimensional tic-tac-toe', 'page': 174, 'dialect': 'generic', 'category': 'board'},
  {'id': 78, 'program': 'QUEEN', 'title': 'Queen', 'description': 'Move a single chess queen vs. the computer', 'page': 178, 'dialect': 'unknown', 'category': 'board'},
  {'id': 79, 'program': 'REVERSE', 'title': 'Reverse', 'description': 'Order a series of numbers by reversing', 'page': 178, 'dialect': 'BASIC-8', 'category': 'puzzle'},
  {'id': 80, 'program': 'ROCKET', 'title': 'Rocket', 'description': 'Land an Apollo capsule on the moon', 'page': 180, 'dialect': 'EduSystem 30', 'category': 'simulation'},
  {'id': 81, 'program': 'ROCKT1', 'title': 'Rocket I', 'description': 'Lunar landing from 500 feet (with plot)', 'page': 183, 'dialect': 'BASIC-8', 'category': 'simulation'},
  {'id': 82, 'program': 'ROCKT2', 'title': 'Rocket II', 'description': 'Very comprehensive lunar landing', 'page': 185, 'dialect': 'generic', 'category': 'simulation'},
  {'id': 83, 'program': 'ROCKSP', 'title': 'Rock Scissors Paper', 'description': 'Game of rock, scissors, paper', 'page': 188, 'dialect': 'BASIC-8', 'category': 'strategy'},
  {'id': 84, 'program': 'ROULET', 'title': 'Roulette', 'description': 'European roulette table', 'page': 189, 'dialect': 'generic', 'category': 'dice'},
  {'id': 85, 'program': 'RUSROU', 'title': 'Russian Roulette', 'description': 'Russian roulette', 'page': 192, 'dialect': 'BASIC-8', 'category': 'dice'},
  {'id': 86, 'program': 'SALVO', 'title': 'Salvo', 'description': 'Destroy an enemy fleet of ships', 'page': 193, 'dialect': 'generic', 'category': 'strategy'},
  {'id': 87, 'program': 'SALVO1', 'title': 'Salvo I', 'description': 'Destroy 4 enemy outposts', 'page': 195, 'dialect': 'BASIC-8', 'category': 'strategy'},
  {'id': 88, 'program': 'SLOTS', 'title': 'Slots', 'description': 'Slot machine (one-arm bandit)', 'page': 196, 'dialect': 'BASIC-8', 'category': 'dice'},
  {'id': 89, 'program': 'SNOOPY', 'title': 'Snoopy', 'description': 'Pictures of Snoopy', 'page': 208, 'dialect': 'No code', 'category': 'art'},
  {'id': 90, 'program': 'SPACWR', 'title': 'Space War', 'description': 'Comprehensive game of spacewar', 'page': 210, 'dialect': 'BASIC-PLUS', 'category': 'action'},
  {'id': 91, 'program': 'SPLAT', 'title': 'Splat', 'description': 'Open a parachute at the last possible moment', 'page': 205, 'dialect': 'EduSystem ?', 'category': 'action'},
  {'id': 92, 'program': 'STARS', 'title': 'Stars', 'description': 'Guess a mystery number - stars give you clues', 'page': 207, 'dialect': 'generic', 'category': 'guessing'},
  {'id': 93, 'program': 'STOCK', 'title': 'Stock Market', 'description': 'Stock market simulation', 'page': 209, 'dialect': 'BASIC-PLUS', 'category': 'simulation'},
  {'id': 94, 'program': 'SYNONM', 'title': 'Synonym', 'description': 'Word synonym drill', 'page': 212, 'dialect': 'BASIC-PLUS', 'category': 'educational'},
  {'id': 95, 'program': 'TARGET', 'title': 'Target', 'description': 'Destroy a target in 3-D space - very tricky', 'page': 214, 'dialect': 'EduSystem ?', 'category': 'action'},
  {'id': 96, 'program': '3DPLOT', 'title': '3D Plot', 'description': 'Plots families of curves - looks 3-dimensional', 'page': 216, 'dialect': 'generic', 'category': 'art'},
  {'id': 97, 'program': 'TICTAC', 'title': 'Tic-Tac-Toe', 'description': 'Tic-tac-toe', 'page': 218, 'dialect': 'BASIC-PLUS', 'category': 'board'},
  {'id': 98, 'program': 'TOWER', 'title': 'Tower', 'description': 'Towers of Hanoi puzzle', 'page': 221, 'dialect': 'BASIC-8', 'category': 'puzzle'},
  {'id': 99, 'program': 'TRAIN', 'title': 'Train', 'description': 'Time-speed-distance quiz', 'page': 223, 'dialect': 'BASIC-8', 'category': 'educational'},
  {'id': 100, 'program': 'TRAP', 'title': 'Trap', 'description': 'Trap a mystery number - computer gives you clues', 'page': 224, 'dialect': 'EduSystem 30', 'category': 'guessing'},
  {'id': 101, 'program': '23MTCH', 'title': '23 Matches', 'description': 'Game of 23 matches - try not to take the last one', 'page': 226, 'dialect': 'generic', 'category': 'strategy'},
  {'id': 102, 'program': 'UGLY', 'title': 'Ugly', 'description': 'Silly profile plot of an ugly woman', 'page': 228, 'dialect': 'BASIC-8', 'category': 'art'},
  {'id': 103, 'program': 'WAR', 'title': 'War', 'description': 'Card game of war', 'page': 230, 'dialect': 'generic', 'category': 'card'},
  {'id': 104, 'program': 'WAR-2', 'title': 'War II', 'description': 'Troop tactics in war', 'page': 232, 'dialect': 'EduSystem 30', 'category': 'strategy'},
  {'id': 105, 'program': 'WEKDAY', 'title': 'Weekday', 'description': 'Facts about your birthday', 'page': 234, 'dialect': 'BASIC-PLUS', 'category': 'educational'},
  {'id': 106, 'program': 'WORD', 'title': 'Word', 'description': 'Word guessing game', 'page': 236, 'dialect': 'BASIC-PLUS', 'category': 'word'},
  {'id': 107, 'program': 'YAHTZE', 'title': 'Yahtzee', 'description': 'Dice game of Yahtzee', 'page': 238, 'dialect': 'BASIC-PLUS', 'category': 'dice'},
  {'id': 108, 'program': 'ZOOP', 'title': 'Zoop', 'description': "BASIC programmer's nightmare", 'page': 243, 'dialect': 'EduSystem 15/30/35', 'category': 'puzzle'}
]

# Add slugs
for g in games:
    g['slug'] = g['program'].lower().replace('-', '').replace(' ', '')

with open('data/games.json', 'w') as f:
    json.dump(games, f, indent=2)
print('Created games.json with', len(games), 'games')
